[meta]
title="Real-time threat Detection - Part 2" 
description="In this notebook we will validate the accuracy of the threat detection model with a test dataset"
icon="browser"
tags=["iot", "cybersecurity", "training", "vectordb"]
destinations=["spaces"]
