[meta]
title="Working with Vector Data"
description="""\
    This example demonstrates the various ways to upload and download
    vector data from SingleStoreDB using Python.
    """
icon="browser"
difficulty="beginner"
tags=["starter", "vectodb", "genai"]
destinations=["spaces"]
minimum_tier="free-shared"
