[meta]
title="InsureGPT: OpenAI and SingleStore for Insurance"
description="Creating an insurance analysis with OpenAI and vectorizing the results into SingleStore."
difficulty="intermediate"
tags=["openai", "langchain"]
icon="database"
minimum_tier="standard"
