[meta]
authors=["chetan-thote"]
title = "SingleStore Now 2024 Raffle"
description = """
    "Explore the power of SingleStore in this interactive notebook by creating an account, loading data, and running queries for a chance to win the SingleStore Now 2024 Raffle!" """
icon = "radar"
difficulty="intermediate"
tags =  ["mongo", "embeddings", "vector", "genai", "kai", "starter"]
lesson_areas=["Kai", "AI"]
destinations = ["spaces"]
minimum_tier="free-shared"
