[meta]
title="Mongo Atlas & SingleStore Kai"
description="""\
    Run your MongoDB queries on SingleStore Kai with no code change. \
    """
icon="database"
difficulty="beginer"
tags=["starter", "mongo", "kai"]
destinations=["spaces"]
minimum_tier="free-shared"
