[meta]
title="Movie Recommendation"
description="""\
    Movie recommendation engine using vectors stored in SingleStore to find your next watch. \
    """
icon="camera-movie"
difficulty="advanced"
tags=["advanced", "vectordb", "genai", "openai"]
destinations=["spaces"]
minimum_tier="standard"
