[meta]
title="Launch Open-Source Apps with LangChain"
description="""\
    LangChain connector to use SingleStoreDB as your vector database for your apps. \
    """
icon="vector-circle"
tags=["vectordb", "genai", "langchain"]
destinations=["spaces"]
